version: '2'
services:
  db:
    container_name: db_10
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - o2-db-data:/var/lib/postgresql/data/pgdata
  web:
    container_name: odoo_12
    image: odoo:12
    depends_on:
      - db
    ports:
      - "$port:8069"
      - "$chat_port:8072"
    volumes:
      - o2-web-data:/var/lib/odoo
      - ./docker:/etc/odoo/
      - ./addons:/mnt/extra-addons
volumes:
  o2-web-data:
  o2-db-data: